services:
  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_USER=asd
      - POSTGRES_PASSWORD=asd
      - POSTGRES_DB=currency
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - db-dataqq:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  pgadmin:
    container_name: pg_admin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - app-network
    ports:
      - "5050:80"
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-dataqq: