CREATE TABLE CURRENCY (
    ID SERIAL PRIMARY KEY,
    CODE VARCHAR(3) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL
);

CREATE TABLE EXCHANGE_RATE_PACK (
    ID SERIAL PRIMARY KEY,
    BASE_CURRENCY_CODE VARCHAR(3) NOT NULL,
    SUCCESS NUMBER(1) NOT NULL,
    API_TIMESTAMP NUMBER(18,0) NOT NULL,
    FETCH_DATE TIMESTAMP NOT NULL
);

CREATE TABLE EXCHANGE_RATE (
    ID SERIAL PRIMARY KEY,
    CURRENCY_CODE VARCHAR(3) NOT NULL,
    RATE NUMBER(25,20) NOT NULL,
    EXCHANGE_RATE_PACK_ID NUMBER(18,0) NOT NULL
);

CREATE TABLE DATA_PROVIDER_CONFIG (
    ID SERIAL PRIMARY KEY,
    PROVIDER_NAME VARCHAR(30) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL
);


INSERT INTO DATA_PROVIDER_CONFIG (PROVIDER_NAME, CREATION_DATE)
VALUES ('fixerIo', CURRENT_DATE());

INSERT INTO CURRENCY (CODE, CREATION_DATE)
VALUES ('EUR', CURRENT_DATE());