CREATE TABLE CURRENCY (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(3) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL
);

CREATE TABLE EXCHANGE_RATE_PACK (
    ID BIGSERIAL PRIMARY KEY,
    BASE_CURRENCY_CODE VARCHAR(3),
    SUCCESS BOOLEAN NOT NULL,
    API_TIMESTAMP BIGINT,
    FETCH_DATE TIMESTAMP NOT NULL
);

CREATE TABLE EXCHANGE_RATE (
    ID BIGSERIAL PRIMARY KEY,
    CURRENCY_CODE VARCHAR(3) NOT NULL,
    RATE DECIMAL(25,20) NOT NULL,
    EXCHANGE_RATE_PACK_ID BIGINT NOT NULL
);

CREATE TABLE DATA_PROVIDER_CONFIG (
    ID BIGSERIAL PRIMARY KEY,
    PROVIDER_NAME VARCHAR(30) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL
);

INSERT INTO DATA_PROVIDER_CONFIG (PROVIDER_NAME, CREATION_DATE)
VALUES ('fixerIo', CURRENT_TIMESTAMP);

INSERT INTO CURRENCY (CODE, CREATION_DATE)
VALUES ('EUR', CURRENT_TIMESTAMP);